# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'Wheel Of Meals' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wheel Of Meals
pod 'lottie-ios'
end